CREATE TABLE import_data (
    field_001 NVARCHAR(100) NOT NULL
  , field_002 NVARCHAR(MAX)     NULL
  , field_003 NVARCHAR(MAX)     NULL
  , field_004 NVARCHAR(MAX)     NULL
  , field_005 NVARCHAR(MAX)     NULL
  , field_006 NVARCHAR(MAX)     NULL
  , field_007 NVARCHAR(MAX)     NULL
  , field_008 NVARCHAR(MAX)     NULL
  , field_009 NVARCHAR(MAX)     NULL
  , field_010 NVARCHAR(MAX)     NULL
  , field_011 NVARCHAR(MAX)     NULL
  , field_012 NVARCHAR(MAX)     NULL
  , field_013 NVARCHAR(MAX)     NULL
  , field_014 NVARCHAR(MAX)     NULL
  , field_015 NVARCHAR(MAX)     NULL
  , field_016 NVARCHAR(MAX)     NULL
  , field_017 NVARCHAR(MAX)     NULL
  , field_018 NVARCHAR(MAX)     NULL
  , field_019 NVARCHAR(MAX)     NULL
  , field_020 NVARCHAR(MAX)     NULL
  , field_021 NVARCHAR(MAX)     NULL
  , field_022 NVARCHAR(MAX)     NULL
  , field_023 NVARCHAR(MAX)     NULL
  , field_024 NVARCHAR(MAX)     NULL
  , field_025 NVARCHAR(MAX)     NULL
  , field_026 NVARCHAR(MAX)     NULL
  , field_027 NVARCHAR(MAX)     NULL
  , field_028 NVARCHAR(MAX)     NULL
  , field_029 NVARCHAR(MAX)     NULL
  , field_030 NVARCHAR(MAX)     NULL
  , field_031 NVARCHAR(MAX)     NULL
  , field_032 NVARCHAR(MAX)     NULL
  , field_033 NVARCHAR(MAX)     NULL
  , field_034 NVARCHAR(MAX)     NULL
  , field_035 NVARCHAR(MAX)     NULL
  , field_036 NVARCHAR(MAX)     NULL
  , field_037 NVARCHAR(MAX)     NULL
  , field_038 NVARCHAR(MAX)     NULL
  , field_039 NVARCHAR(MAX)     NULL
  , field_040 NVARCHAR(MAX)     NULL
  , field_041 NVARCHAR(MAX)     NULL
  , field_042 NVARCHAR(MAX)     NULL
  , field_043 NVARCHAR(MAX)     NULL
  , field_044 NVARCHAR(MAX)     NULL
  , field_045 NVARCHAR(MAX)     NULL
  , field_046 NVARCHAR(MAX)     NULL
  , field_047 NVARCHAR(MAX)     NULL
  , field_048 NVARCHAR(MAX)     NULL
  , field_049 NVARCHAR(MAX)     NULL
  , field_050 NVARCHAR(MAX)     NULL
  , field_051 NVARCHAR(MAX)     NULL
  , field_052 NVARCHAR(MAX)     NULL
  , field_053 NVARCHAR(MAX)     NULL
  , field_054 NVARCHAR(MAX)     NULL
  , field_055 NVARCHAR(MAX)     NULL
  , field_056 NVARCHAR(MAX)     NULL
  , field_057 NVARCHAR(MAX)     NULL
  , field_058 NVARCHAR(MAX)     NULL
  , field_059 NVARCHAR(MAX)     NULL
  , field_060 NVARCHAR(MAX)     NULL
  , field_061 NVARCHAR(MAX)     NULL
  , field_062 NVARCHAR(MAX)     NULL
  , field_063 NVARCHAR(MAX)     NULL
  , field_064 NVARCHAR(MAX)     NULL
  , field_065 NVARCHAR(MAX)     NULL
  , field_066 NVARCHAR(MAX)     NULL
  , field_067 NVARCHAR(MAX)     NULL
  , field_068 NVARCHAR(MAX)     NULL
  , field_069 NVARCHAR(MAX)     NULL
  , field_070 NVARCHAR(MAX)     NULL
  , field_071 NVARCHAR(MAX)     NULL
  , field_072 NVARCHAR(MAX)     NULL
  , field_073 NVARCHAR(MAX)     NULL
  , field_074 NVARCHAR(MAX)     NULL
  , field_075 NVARCHAR(MAX)     NULL
  , field_076 NVARCHAR(MAX)     NULL
  , field_077 NVARCHAR(MAX)     NULL
  , field_078 NVARCHAR(MAX)     NULL
  , field_079 NVARCHAR(MAX)     NULL
  , field_080 NVARCHAR(MAX)     NULL
  , field_081 NVARCHAR(MAX)     NULL
  , field_082 NVARCHAR(MAX)     NULL
  , field_083 NVARCHAR(MAX)     NULL
  , field_084 NVARCHAR(MAX)     NULL
  , field_085 NVARCHAR(MAX)     NULL
  , field_086 NVARCHAR(MAX)     NULL
  , field_087 NVARCHAR(MAX)     NULL
  , field_088 NVARCHAR(MAX)     NULL
  , field_089 NVARCHAR(MAX)     NULL
  , field_090 NVARCHAR(MAX)     NULL
  , field_091 NVARCHAR(MAX)     NULL
  , field_092 NVARCHAR(MAX)     NULL
  , field_093 NVARCHAR(MAX)     NULL
  , field_094 NVARCHAR(MAX)     NULL
  , field_095 NVARCHAR(MAX)     NULL
  , field_096 NVARCHAR(MAX)     NULL
  , field_097 NVARCHAR(MAX)     NULL
  , field_098 NVARCHAR(MAX)     NULL
  , field_099 NVARCHAR(MAX)     NULL
  , field_100 NVARCHAR(MAX)     NULL
  , CONSTRAINT pk_import_data PRIMARY KEY(field_001)
)
